### ISSUE TITLE
error in get_minikappa.py

### ISSUE THREAD

**Issue by DFT13** [yimavxia/Minikappa#1]
Dear Xia
        Thanks you develope the significant contribution in thermal transport. Running get_minikappa.py in example fold, I encountered the following error (the version of phonopy  is 2.17.1), can you give me some advice? Thanks.

Best wish

Number of atoms in primitive cell: 2
Traceback (most recent call last):
  File "get_minikappa.py", line 16, in <module>
    list_taufactor = [2.0])
  File "/dg_workfs/CSG/qyxie/Minikappa-main/scripts/example/conductivity.py", line 95, in get_minikappa_phonopy
    tmpv=(gvfull[iq,i,j,k]*gvfull[iq,j,i,kp]).real
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

**Comment by yimavxia** [comment]
Hello,

Did you replace the original group_velocity.py with the one that I modified (under Minikappa/scripts/)? The error you showed indicates you were using the original group_velocity.py, which produces 3-dimensional array.

**Comment by DFT13** [comment]
Thank you very much! this issue is sovled according your advice. in additional, I want to konw how to obtain the effective second-order force constant of phonopy format through SCPH theory anahrmonically renormalization for the subsequent calculation of the fourphonon scattering rate. As far as I know, alamode package only supports the calculation of three-phonon scattering rate based on PBTE and SCPH. Could you give me some suggestions?
